Repository orca-services/cakephp-heartbeat, pull requests merged in 2019-10, with the labels that each got.

#24 Improve readability of configuration
  docs/Configuration.md
Labels: documentation, enhancement

#25 Add CakePHP CodeSniffer
  CHANGELOG.md
  composer.json
  composer.lock
  phpcs.xml.dist
  src/Controller/HeartbeatController.php
  src/Heartbeat/Heartbeat.php
  src/Heartbeat/Sensor.php
  src/Heartbeat/Sensor/Config.php
  src/Heartbeat/Sensor/DBConnection.php
  src/Heartbeat/Sensor/DBUpToDate.php
  src/Heartbeat/Sensor/DebugMode.php
  src/Plugin.php
Labels: dependencies, enhancement

#22 Sensor status now indicates whether the result were fetched from cache
  CHANGELOG.md
  README.md
  src/Heartbeat/Sensor.php
  src/Heartbeat/Sensor/Status.php
  src/Template/Element/status_table.ctp
  src/Template/Heartbeat/json/index.ctp
  tests/TestCase/Heartbeat/Sensor/ConfigTest.php
  tests/TestCase/Heartbeat/Sensor/StatusTest.php
  tests/TestCase/Heartbeat/SensorTest.php
  tests/TestCase/Sensor/DummySensor.php
Labels: enhancement
